### ISSUE TITLE
Commitlint does not work anymore

### ISSUE THREAD

**Issue by wzrdtales** [ahmed-taj/commitlint-bot#10]
For some reason commitlint is not functioning anymore, just wanted to now first if I am the only one experiencing this?

See https://github.com/db-migrate/node-db-migrate/pull/537 for reference, which is missing the commitlint output for an unknown reason. Have reinstalled the bot already to test if this would have been the source of the problem, but unfortunately it seems to be something different. Nothing was changed from the last time it worked though...

**Comment by ahmed-taj** [comment]
Hey @wzrdtales, thanks for opening this :sparkles:

So sad to hear this :disappointed: again ( #9 ). 

I've two bots in my **free** Heroku plan: **commitlint** and [**DEP**](https://github.com/ahmed-taj/dep) but both got popular recently and it seems the plan can't handle the load any longer.

Both are forced sleep now :/

![selection_072](https://user-images.githubusercontent.com/12673605/37976180-34a56ec4-31e1-11e8-8a2b-7cae4ae7c689.png)

I can't afford a paid plan so If you would like to host your own instance of this app then [this guide]( https://github.com/ahmed-taj/commitlint-bot/blob/master/docs/deploy.md) will help.

Sorry for the inconvenience. Suggestions are welcome!

**Comment by wzrdtales** [comment]
Thanks for the information :) That helps! But still suggestions:

Contact heroku, tell them what it is for and if they're willing to sponsor.

Other alternatives, get money for the infrastructure through:
https://salt.bountysource.com/
https://opencollective.com/

Or some other alternative. For the latter ones you will depending on where you live require to stick by to your local tax laws.

I will setup my own instance now, so thank you for your response on this :)

**Comment by wzrdtales** [comment]
Ahh forgot openshift, they actally have a program for such stuff:

https://www.openshift.com/grants/

**Comment by ahmed-taj** [comment]
@wzrdtales thanks for those suggestions. I will check them out.
