### ISSUE TITLE
Use details to advise how to fix

### ISSUE THREAD

**Issue by JasonEtco** [ahmed-taj/commitlint-bot#2]
Hey! This is really cool! I had a quick drive-by thought; with the [GPG](https://github.com/jarrodldavis/probot-gpg) Probot App we've talked about how to fix a failed status. As in, what happens when someone commits without verifying their GPG key?

I think there's a similar situation with the **commitlint-bot**; if I commit a message that wouldn't pass, and the PR gets a ❌ , maybe you can use the Details pane to suggest ways to fix it. This way, it becomes a way for folks to learn on the spot and not be blocked by something they don't know how to do with Git.

**Comment by ahmed-taj** [comment]
@JasonEtco glad you like it!

I was thinking the same, I will do my best! Suggestions are welcome ;)

**Comment by ahmed-taj** [comment]
@JasonEtco  I've been thinking for a while on this. As far I know these are the necessary information here:

* **What is wrong with my messages**
I've already included the error messages from `commitlint` output.
* **How should it look**
This is missing, I need to point them to somewhere where they can find the correct commit format, which I think should be written in the CONTRIBUTING file, or I can just point them to [ConventionalCommits]() website.
* **How to correct it (Git)**
This is also missing part, I think I need to include a link to this GitHub's [help page](https://help.github.com/articles/changing-a-commit-message)

I think I may include the "How should it look" link as a [`target_url` of the commit status]( https://developer.github.com/v3/repos/statuses/#create-a-status)

Also, I need to add a hint to "How to correct it" in the details comment so it will look like the following:

> There were the following issues with this Pull Request
> 
> * Commit: 39962ce
>    - ✖ message may not be empty
>    - ✖ type may not be empty
> 
> You need to [modify the commit messages](https://help.github.com/articles/changing-a-commit-message)  to fix the above errors.

What do you think?

/cc @wzrdtales your feedback is welcomed

**Comment by ahmed-taj** [comment]
I have made some progress in #4 , please check out!
